# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker Image

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*' ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: blecossois/mon-frontend, blecossois/mon-backend

      - name: Build and push frontend Docker image
        id: build-and-push-frontend
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          file: Utils/frontend.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push backend Docker image
        id: build-and-push-backend
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          file: .Utils/backend.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation for frontend docker image
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: index.docker.io/blecossois/mon-frontend
          subject-digest: ${{ steps.build-and-push-frontend.outputs.digest }}
          push-to-registry: true

      - name: Generate artifact attestation for backend docker image
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: index.docker.io/blecossois/mon-backend
          subject-digest: ${{ steps.build-and-push-backend.outputs.digest }}
          push-to-registry: true

      - name: Send discord notifications
        if: success()  # Exécuter seulement si le build est réussi
        env:
            DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
            curl -H "Content-Type: application/json" \
            -X POST \
            -d '{"content": "🚀 **Build Docker réussi !**\n\n📦 Les images sont désormais sur [Docker Hub 🔗](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"}' \